<?php
return [
	0 => [
		'title' => 'Продажи по дням',
		'blocks' => [
			[
				'title' => [
					'date' => '08.10.2021',
					'operator' => '-',
					'number_sold' => '34 шт.',
					'sum_sold' => '2323',
					'number_return' => '880 руб',
					'sum_return' => '234',
					'isTitle' => true
				],
				'data' => [
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
				]
			],
			[
				'title' => [
					'date' => '08.10.2021',
					'operator' => '-',
					'number_sold' => '34 шт.',
					'sum_sold' => '2323',
					'number_return' => '880 руб',
					'sum_return' => '234',
					'isTitle' => true
				],
				'data' => [
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
				]
			],
			[
				'title' => [
					'date' => '08.10.2021',
					'operator' => '-',
					'number_sold' => '34 шт.',
					'sum_sold' => '2323',
					'number_return' => '880 руб',
					'sum_return' => '234',
					'isTitle' => true
				],
				'data' => [
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
				]
			],
			[
				'title' => [
					'date' => '08.10.2021',
					'operator' => '-',
					'number_sold' => '34 шт.',
					'sum_sold' => '2323',
					'number_return' => '880 руб',
					'sum_return' => '234',
					'isTitle' => true
				],
				'data' => [
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
				]
			],
			[
				'title' => [
					'date' => '08.10.2021',
					'operator' => '-',
					'number_sold' => '34 шт.',
					'sum_sold' => '2323',
					'number_return' => '880 руб',
					'sum_return' => '234',
					'isTitle' => true
				],
				'data' => [
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
				]
			],
			[
				'title' => [
					'date' => '08.10.2021',
					'operator' => '-',
					'number_sold' => '34 шт.',
					'sum_sold' => '2323',
					'number_return' => '880 руб',
					'sum_return' => '234',
					'isTitle' => true
				],
				'data' => [
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
				]
			],
			[
				'title' => [
					'date' => '08.10.2021',
					'operator' => '-',
					'number_sold' => '34 шт.',
					'sum_sold' => '2323',
					'number_return' => '880 руб',
					'sum_return' => '234',
					'isTitle' => true
				],
				'data' => [
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
					[
						'date' => '',
						'operator' => 'КАССИР НБО',
						'number_sold' => '34 шт.',
						'sum_sold' => '2323',
						'number_return' => '880 руб',
						'sum_return' => '234',
						'isSub' => true,
					],
				]
			],
		]
	],
];
